#!/bin/bash

# Build Index
make

echo "Ready to test"

# Launch test server in background
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../../trilite ../../bin/dxr-serve.py --port 3571 target 2>/dev/null &

# Give the server some time to start
# Not starting in a sec is also a bug :)
sleep 10;

# This is where we get an interesting result
./search-test.py
result=$?

# Make sure we kill the server
kill %1

make clean

exit $result
