#!/bin/bash

# Build Index
make

echo "Ready to test"

# Launch test server in background
pushd target/server
./test-server.py --port 3571 2>/dev/null &
popd

# Give the server some time to start
# Not starting in a sec is also a bug :)
sleep 1;

# This is where we get an interesting result
./search-test.py
result=$?

# Make sure we kill the server
kill %1

make clean

exit $result
