#!/bin/sh

# Change to tokenizer directory
cd ../../sqlite-tokenizer;

# Run make check
make check;
result=$?;

# Cleanup after the test
echo "make clean"
make clean;

# Exit with result
exit $result;
